# Generated by Django 3.0.4 on 2020-03-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='hunter',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='body',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='title',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='url',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='statement',
            name='statement_text',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesVotes_total', models.IntegerField(default=0)),
                ('noVotes_total', models.IntegerField(default=0)),
                ('response_date', models.DateTimeField()),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.Statement')),
            ],
        ),
    ]
