# Generated by Django 3.0.4 on 2020-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_auto_20200321_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('url', models.TextField()),
                ('icon', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('DontCare', 'Dontcare'), ('DontKnow', 'Dontknow')], default='DontKnow', max_length=10),
        ),
        migrations.AddField(
            model_name='statement',
            name='hashtags',
            field=models.ManyToManyField(related_name='hashtags', to='statements.Hashtag'),
        ),
    ]
