# Generated by Django 3.0.4 on 2020-03-22 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statements', '0004_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='noVotes_total',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='yesVotes_total',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='voters',
        ),
        migrations.AddField(
            model_name='response',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='agreeUsers',
            field=models.ManyToManyField(related_name='agreeUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='disagreeUsers',
            field=models.ManyToManyField(related_name='disagreeUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='dontcareUsers',
            field=models.ManyToManyField(related_name='dontcareUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='dontknowUsers',
            field=models.ManyToManyField(related_name='dontknowUsers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
