# Generated by Django 3.0.4 on 2020-03-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0006_auto_20200322_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response',
            new_name='answer',
        ),
    ]
