# Generated by Django 3.0.4 on 2020-03-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0007_auto_20200322_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='response_date',
        ),
    ]
