# Generated by Django 3.0.4 on 2020-03-22 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0008_remove_response_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
