# Generated by Django 3.0.4 on 2020-03-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0009_response_response_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='answer',
            new_name='agree',
        ),
        migrations.AddField(
            model_name='response',
            name='disagree',
            field=models.IntegerField(default=0),
        ),
    ]
