# Generated by Django 3.0.4 on 2020-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0010_auto_20200323_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='icon',
            field=models.ImageField(blank=True, default='static/statements/opinion_choice.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='statement',
            name='iconAgree',
            field=models.ImageField(blank=True, default='static/statements/opinion_choice.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='statement',
            name='iconDisagree',
            field=models.ImageField(blank=True, default='static/statements/opinion_choice.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='statement',
            name='image',
            field=models.ImageField(blank=True, default='static/statements/opinion_choice.png', null=True, upload_to='images/'),
        ),
    ]
