# Generated by Django 3.0.4 on 2020-03-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0011_auto_20200323_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='iconAgree',
            field=models.ImageField(blank=True, default='static/statements/agree.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='iconDisagree',
            field=models.ImageField(blank=True, default='static/statements/disagree.png', null=True, upload_to='images/'),
        ),
    ]
